# Generated by Django 4.2.8 on 2024-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charcode", models.CharField(max_length=3, verbose_name="Валюта")),
                ("date", models.DateField(verbose_name="Дата")),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="Курс"
                    ),
                ),
            ],
            options={
                "verbose_name": ("Курс валюты",),
                "unique_together": {("charcode", "date")},
            },
        ),
    ]
